anti-click-spam-delay: 500
anti-interact-spam-delay: 500

messages:
  no-levels: "&cNot enough levels. You need %levels% levels to use this item!"
  no-balance: "&cNot enough money. You need $%price% to use this item!"
  no-economy: "&cThis item cannot be used because vault is not installed!"
  list-usage: "&c/%label% list <menus/hotbars>"
  list-invalid-argument: "&cInvalid argument: %argument%\nAvailable: hotbars, menus"
  hotbar-list-header: "&aAvailable hotbars:"
  hotbar-list-entry: "&b%entry%"
  menu-list-header: "&aAvailable menus:"
  menu-list-entry: "&b%entry%"
  no-hotbars: "&cThere are no hotbars configured!"
  no-menus: "&cThere are no menus configured!"
  menu-usage: "&c/%label% menu <menu> [player]"
  opened-menu: "&aOpened menu&b %menu%&a!"
  unexistant-menu: "&cThe menu %menu% does not exist!"
  opened-menu-other: "&aOpened menu &b%menu%&a for &b%player%&a!"
  hotbar-usage: "&c/%label% hotbar <hotbar> [player]"
  no-console: "&cYou cannot use this command from the console!"
  opened-hotbar: "&aOpened hotbar&b %hotbar%&a!"
  no-subcommand: "&cNo subcommand found: %argument%\nPossible commands: reload, menu, hotbar, list"
  interfacemaker-usage: "&cInterfaceMaker by LinsaFTW\nPossible commands: reload, menu, hotbar, list"
  unexistant-hotbar: "&cThe hotbar %hotbar% does not exist!"
  offline: "&cThe player is offline!"
  opened-hotbar-other: "&aOpened hotbar &b%hotbar%&a for &b%player%&a!"
  reload: "&aThe plugin has been reloaded!"
  click-cooldown: "&cWait before clicking again!"
  interact-cooldown: "&cWait before interacting again!"