name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
softdepend: [ "PlaceholderAPI", "Vault" ]
api-version: 1.13
commands:
  interfacemaker:
    aliases: ["im"]
    description: "InterfaceMaker is a revolutionary interface manager plugin."