name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
depend: [ "PlaceholderAPI" ]
commands:
  interfacemaker:
    aliases: ["im"]
    description: "InterfaceMaker is a revolutionary interface manager plugin."