hotbar-settings:
  auto-refresh: 5
  give-on-spawn: true

example-menu:
  material: NETHER_STAR
  position-x: 2
  name: "&8&l» &6&lExample Menu &8&l«"
  lore:
    - "&7Opens the example &bInterfaceMaker &7menu."
  actions:
    - 'open-menu: default'

permission-item:
  material: BLAZE_ROD
  position-x: 3
  name: "&8&l» &a&lToggle Flight &8&l«"
  permission: "item.fly"
  permission-message: "&aYou have to be VIP to use this!"
  actions:
    - 'player: fly'

secret-item:
  material: EMERALD
  position-x: 5
  name: "<RAINBOW1>Secret Item</RAINBOW>"
  view-permission: 'my.custom.permission'
  enchantments:
    - "luck, 1"
  actions:
    - 'tell: <RAINBOW1>You has clicked the SECRET item</RAINBOW>'

virtual-crafting-table:
  material: WORKBENCH
  position-x: 7
  name: "&8&l» &b&lOpen Crafting Table &8&l«"
  price: 100
  lore:
    - "&7Price: &b100$"
  actions:
    - 'player: workbench'

virtual-anvil:
  material: ANVIL
  position-x: 8
  name: "&8&l» &b&lOpen Anvil &8&l«"
  price: 100
  lore:
    - "&7Price: &b100$"
  actions:
    - 'player: anvil'